server:
  port: 8080
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      order_inserts: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
          batch_size: 50
      temp:
          use_jdbc_metadata_defaults: false
      
  datasource:
    url: jdbc:postgresql://localhost:5432/tour_of_heroes
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: monsolis
  messages:
    basename: bundles/languageBundle
    